default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo
  password: demo
  host: localhost
  port: 5433  # Specify the port number here

development:
  <<: *default
  database: demo

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: demo
